spring:
  application:
    name: content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.165.36:3306/xc148_content?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: 237512610
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


